units:
  # Size of each key. cx and cy for choc, u and U for MX.
  kx: cx
  ky: cy
  # key spread and padding
  px: 1.04kx
  py: 1.04ky
  # From that, get the spacing between keys
  ksx: px-kx
  ksy: py-ky
  lpx: px + 1
  
  # Stagger for all of the different columns
  stagger1: py # ring column one key above the pinky column
  stagger2: 0.3py # middle column .3 key above the ring column
  stagger3: -0.6py # index
  stagger4: -0.2py # inner

  xiao_length: 21
  xiao_width: 17.78

  trrs_width: 6.1

  ct: 1.5 # case thickness

points:
  key:
    spread: 1px
    padding: 1py
  zones:
    matrix:
      columns:
        pinky:
          key:
            column_net: P5
        ring:
          key:
            stagger: stagger1
            column_net: P3
        middle:
          key:
            stagger: stagger2
            column_net: P2
        index:
          key:
            stagger: stagger3
            column_net: P1
        inner:
          key:
            stagger: stagger4
            column_net: P0
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P9
        top:
          row_net: P8
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-2px, -py]
      columns:
        inner:
          key:
            column_net: P2
        middle:
          key:
            column_net: P1
        home:
          key:
            column_net: P0
      rows:
        thumb:
          row_net: P4

outlines:
  board_noround:
    keys:
      what: rectangle
      where: true
      size: [lpx, py]
    mcu:
      what: polygon
      points:
        - ref: matrix_middle_top # Top left
          shift: [-2px-0.5lpx, 0.5py]
        - ref: matrix_middle_top # Top right
          shift: [0, 0.5py]
        - ref: matrix_middle_top # Bottom right (in board)
          shift: [0, -1py]
        - ref: matrix_middle_top # Bottom left
          shift: [-2px-0.5lpx, -1py]
    battery:
      what: polygon
      points:
        - ref: matrix_middle_home # Top left (in board)
          shift: [-0.5lpx, 0]
        - ref: matrix_inner_home # Top right (in board)
          shift: [0.5lpx, 0]
        - ref: thumbfan_home_thumb # Bottom right
          shift: [0.5lpx, -0.5py]
        - ref: thumbfan_inner_thumb # Bottom left
          shift: [-0.5lpx, -0.5py]
    logo:
      what: polygon
      points:
        - ref: matrix_pinky_bottom # Top left (in board)
          shift: [0, py]
        - ref: matrix_pinky_bottom # Top right (in board)
          shift: [2px, py]
        - ref: matrix_pinky_bottom # Bottom right (in board)
          shift: [2px, -0.5py]
        - ref: matrix_pinky_bottom # Bottom left (in board)
          shift: [0, -0.5py]
    trrs:
      what: polygon
      points:
        - ref: matrix_inner_top # Top left
          shift: [-2px, 0.5py+trrs_width+ksy]
        - ref: matrix_inner_top # Top right
          shift: [0.5lpx, 0.5py+trrs_width+ksy]
        - ref: matrix_inner_top # Bottom right (in board)
          shift: [0.5lpx, -1py]
        - ref: matrix_inner_top # Bottom left
          shift: [-2px, -1py]

  board:
    - what: outline
      name: board_noround
      fillet: 1

  top_plate_base:
    keys:
      what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-0.5kx, 0.5ky]
        - ref: matrix_pinky_top
          shift: [0.5kx+ksx, 0.5ky]
        - ref: matrix_ring_top
          shift: [-0.5kx, 0.5ky]
        - ref: matrix_ring_top
          shift: [0.5kx+ksx, 0.5ky]
        - ref: matrix_middle_top
          shift: [-0.5kx, 0.5ky]
        - ref: matrix_middle_top
          shift: [0.5kx, 0.5ky]
        - ref: matrix_index_top
          shift: [-0.5kx-ksx, 0.5ky]
        - ref: matrix_index_top
          shift: [0.5kx, 0.5ky]
        - ref: matrix_inner_top
          shift: [-0.5kx-ksx, 0.5ky]
        - ref: matrix_inner_top
          shift: [0.5kx, 0.5ky]
        - ref: thumbfan_home_thumb
          shift: [0.5kx, -0.5ky]
        - ref: thumbfan_middle_thumb
          shift: [-0.5kx, -0.5ky]
        - ref: matrix_index_bottom
          shift: [-0.5kx, -0.5ky]
        - ref: matrix_middle_bottom
          shift: [0.5kx+ksx, -0.5ky]
        - ref: matrix_middle_bottom
          shift: [-0.5kx-ksx, -0.5ky]
        - ref: matrix_ring_bottom
          shift: [0.5kx, -0.5ky]
        - ref: matrix_ring_bottom
          shift: [-0.5kx-ksx, -0.5ky]
        - ref: matrix_pinky_bottom
          shift: [0.5kx, -0.5ky]
        - ref: matrix_pinky_bottom
          shift: [-0.5kx, -0.5ky]
  top_plate:
    top_plate_base:
      what: outline
      name: top_plate_base
      fillet: 1
    cutouts:
      what: rectangle
      where: true
      size: 14
      operation: subtract
  case_base_raw:
    - what: polygon
      points:
        - ref: matrix_middle_top # Top left
          shift: [-2px-0.5lpx-ct, 0.5py+ct]
        - ref: matrix_middle_top # Top right
          shift: [2px+0.5lpx+ct, 0.5py+ct]
        - ref: thumbfan_home_thumb # Bottom right
          shift: [0.5lpx+ct, -0.5py-ct]
        - ref: thumbfan_inner_thumb # Bottom left
          shift: [-2px-0.5lpx-ct, -0.5py-ct]
  case_base:
    - what: outline
      name: case_base_raw
      fillet: 1
  case_walls:
    - what: outline
      name: case_base
    - what: outline
      operation: subtract
      name: board

cases:
  left_bottom:
    - what: outline
      name: case_base
      extrude: ct
      shift: [0, 0, -1.5]
    - what: outline
      name: case_walls
      extrude: 1.85 + 1.6 + 5 # hotswap socket + pcb + switch
    - what: outline
      name: top_plate
      extrude: 1.3
      shift: [0, 0, 1.85 + 1.6 + 0.9] # 0.9 is the distance between the top plate and the pcb



pcbs:
  main:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3py]
      diode_via_1:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [2.8, -0.3py]
      diode_via_2:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-2.8, -0.3py]
      key_via_1:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, 3.67]
      key_via_2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [0, 2.67]
      xiao_flippable:
        what: xiao_flippable
        where:
          ref: matrix_pinky_top
          shift: [0.5px-0.5ksx-xiao_width-(kx-xiao_width)/2, 0.5py+0.5ksy]
          rotate: -90
      raw_pad:
        what: pad
        where:
          ref: matrix_pinky_top
          shift: [0, 0.5py]
        params:
          net: RAW
          width: 1.5
          height: 1.5
      battery_pads:
        what: battery_pad
        where:
          ref: matrix_index_bottom
          shift: [0, -0.5ky-2]
          rotate: 0
        params:
          plus: BAT+
          minus: GND
      slider_f:
        what: slider
        where:
          ref: matrix_middle_top
          shift: [-1px, 0.5px-3]
        params:
          from: BAT+
          to: RAW
          side: F
      slider_b:
        what: slider
        where:
          ref: matrix_middle_top
          shift: [-1px, 0.5px-3]
        params:
          from: BAT+
          to: RAW
          side: B
      trrs:
        what: trrs
        where:
          ref: matrix_inner_top
          shift: [7.86, 0.5ky+0.70+ksy]
          rotate: -90
        params:
          reverse: true
          symmetric: true
          A: VCC5
          B: VCC5 # overlaps with A
          C: GND
          D: P7
      logo:
        what: logo
        where:
          ref: matrix_ring_bottom
          shift: [0, -1py]
        params:
          # Remove F.Paste if you want to use a stencil when soldering!
          # This just allows us to see the correct color in KiCad's 3d viewer.
          layers: [F.Cu, F.Paste, F.Mask]
      monkey:
        what: monkey
        where:
          # In middle of MCU
          ref: matrix_pinky_top
          shift: [-1.5, 1py+2.5]
          rotate: 90
  top_plate:
    outlines:
      top_plate:
        outline: top_plate
